contact_book/contact_book/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.Home.as_view(), name="home"),
    path('modify/<int:id>/', views.modify_person, name='modify'),
    path('show/<int:id>/', views.PersonInfo.as_view(), name='show'),
    path('delete/<int:id>/', views.delete_person, name='delete_person'),
    path('groups/', views.Groups.as_view(), name='groups'),
    path('group/<int:id>/', views.GroupInfo.as_view(), name='group_info'),
    path('group_delete/<int:id>/', views.delete_group, name="delete_group"),
    path('delete-phone/<int:person_id>/<int:number_id>',
         views.delete_phone, name='delete_phone'),
    path('delete-email/<int:person_id>/<int:email_id>',
         views.delete_email, name='delete_email'),
    path('delete-person-group/<int:person_id>/<int:group_id>/',
         views.delete_person_group, name='delete_person_group'),
    path('add-contact/', views.AddContact.as_view(), name="add_contact"),
    path('add-group/', views.AddGroup.as_view(), name="add_group"),

]

contact_book/app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator


# potem zapytac tomka czy jest dopuszczalne tworzenie m2m w 2 grupach tak żeby jedna odwoływala sie do drugiej
# w sensie Group będzie miała kolumne people a Person będzie miało kolumne groups


class Group(models.Model):
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(
        'app.Person', verbose_name="Group members", blank=True)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    groups = models.ManyToManyField(
        'app.Group', verbose_name="Groups", blank=True)

    def __str__(self):
        return f"{self.name} {self.surname}"


CHOICES = (
    (1, 'Home'),
    (2, 'Business')
)


class Email(models.Model):
    adress = models.EmailField(unique=True)
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, verbose_name="email adress")
    email_type = models.IntegerField(
        choices=CHOICES, verbose_name="email type")

    def __str__(self):
        return f"{self.adress}-{self.person.name} {self.person.surname}"


class Phone(models.Model):
    number = models.CharField(
        max_length=12,
        validators=[
            RegexValidator(r'^\d{9}$|^\d{3} \d{3} \d{3}$',
                           'Invalid number pattern'),
        ], verbose_name="Phone number", unique=True)
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, verbose_name="Person")
    phone_type = models.IntegerField(
        choices=CHOICES, verbose_name="Phone type")

    def __str__(self):
        return f"{self.number}-{self.person.name} {self.person.surname}"

contact_book/app/templates/add_contact.html
{% extends 'base.html' %}
{% block content %}
<p>{{ msg }}</p>
<h1>Add new contact</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Contact">
</form>


{% endblock %}

contact_book/app/templates/add_group.html
{% extends 'base.html' %}
{% block content %}
<p>{{ msg }}</p>
<h1>Add group</h1>

<form method="POST">
    {% csrf_token %}
    <label for="">Group Name: </label>
    <input type="text" name='name'>
    <input type="submit" value="Add Group">
</form>
{% endblock %}

contact_book/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

</head>

<body>
    <header>
        <nav class="navbar navbar-dark bg-primary navbar-expand-md">
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#mainmenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" id="submenu">Users</a>

                        <div class="dropdown-menu">
                            <a href="{% url 'home' %}" class="dropdown-item">All Contacts</a>
                            <a href="{% url 'add_contact' %}" class="dropdown-item">Add Contact</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" id="submenu">Groups</a>

                        <div class="dropdown-menu">
                            <a href="{% url 'groups' %}" class="dropdown-item">All Groups</a>
                            <a href="{% url 'add_group' %}" class="dropdown-item">Add Group</a>
                        </div>
                    </li>
                </ul>

            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

contact_book/app/templates/groupinfo.html
{% extends 'base.html' %}
{% block content %}
<h1>Group name: {{ group.name }}</h1>
<h2>Members</h2>
<ul>
    {% for person in members %}
    <li>
        <h2><a href="{% url 'show' person.id %}">{{ person.name }} {{ person.surname }}</a></h2>
    </li>
    {% endfor %}
</ul>


{% endblock %}

contact_book/app/templates/groups.html
{% extends 'base.html' %}
{% block content %}
<p>{{ msg }}</p>
<h1>Groups</h1>
<ul>
    {% for group in groups %}
    <li>
        <h2><a href="{% url 'group_info' group.id %}">{{ group.name }}</a></h2>
        <a href="{% url 'delete_group' group.id %}">Remove</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

contact_book/app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Witaj na stronie głównej</h1>
<h2>Lista kontaktów</h2>
<ul>
    {% for person in people %}
    <li>
        <h2><a href="{% url 'show' person.id %}">{{ person.name }} {{ person.surname }}</a></h2>
        <a href="{% url 'modify' person.id %}">Edit</a>
        <a href="{% url 'delete_person' person.id %}">Delete</a>
    </li>
    <br>
    {% endfor %}
</ul>
{% endblock %}

contact_book/app/templates/modifyperson.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    <p>{{ msg }}</p>
    <h1>Modify contact</h1>
    <form method='POST'>
        {% csrf_token %}
        <label for="">Name</label>
        <input type="text" name="name" value="{{ person.name }}">
        <br>
        <label for="">Surname</label>
        <input type="text" name="surname" value="{{ person.surname }}">
        <input type="submit" name="modify" value="Update">
    </form>
    <br>
    <h2>Phone(s)</h2>
    <br>
    {% for phone in phones %}
    <p>{{ phone.number }} - {{ phone.get_phone_type_display }}</p>
    <p><a href="{% url 'delete_phone' person.id phone.id %}">Delete phone number</a></p>
    <br>
    {% endfor %}
    <h2>Email(s)</h2>
    <br>
    {% for email in emails %}
    <p>{{ email.adress }} - {{ email.get_email_type_display }}</p>
    <p><a href="{% url 'delete_email' person.id email.id %}">Delete email adress</a></p>
    <br>
    {% endfor %}
    <h2>Group(s)</h2>
    {% for group in person_groups %}
    <p>{{ group.name }}</p>
    <p><a href="{% url 'delete_person_group' person.id group.id %}">Delete group</a></p>
    {% endfor %}


    <br><br><br>

    <form method="POST">
        {% csrf_token %}
        <h2>Add new group</h2>
        <label for="">Group name: </label>
        <select name="new_group">
            <option value="None" selected></option>
            {% for group in groups %}
            <option value="{{ group.id }}">{{ group.name }}</option>
            {% endfor %}
        </select>
        <input type="submit" name="modify" value="Add group">
    </form>
    <br>
    <form method="post">
        {% csrf_token %}
        <h2>Add new phone</h2>
        <label for="">Number</label>
        <input type="text" name="add_number" pattern="\d{9}|\d{3} \d{3} \d{3}">
        <label for="">Type</label>
        <select name="number_type">
            <option value="None" selected></option>
            {% for type in types %}
            <option value="{{ type.0 }}">{{ type.1 }}</option>
            {% endfor %}
        </select>
        <input type="submit" name="modify" value="Add Phone">
    </form>
    <br>
    <form method="post">
        {% csrf_token %}
        <h2>Add new email adress</h2>
        <label for="">Email adress:</label>
        <input type="email" name="add_email">
        <label for="">Type</label>
        <select name="email_type">
            <option value="None" selected></option>
            {% for type in types %}
            <option value="{{ type.0 }}">{{ type.1 }}</option>
            {% endfor %}
        </select>
        <input type="submit" name="modify" value="Add Email">
    </form>
</div>
{% endblock %}

contact_book/app/templates/personinfo.html
{% extends 'base.html' %}
{% block content %}
<h1>Contact informations</h1>
<p>Name: {{ person.name }}</p>
<p>Surname: {{ person.surname }}</p>
<h3>Phone number/numbers: </h3>
{% for phone in phones %}
<ul>
    <li>Number: {{ phone.number }}</li>
    <p>Phone Type: {{ phone.get_phone_type_display }}</p>
</ul>
{% endfor %}
<h3>Email adress/adresses: </h3>
{% for email in emails %}
<ul>
    <li>Adress: {{ email.adress }}</li>
    <li>Email Type: {{ email.get_email_type_display }}</li>
</ul>
{% endfor %}
<h3>Groups</h3>
{% for group in person_groups %}
<ul>
    <li>{{ group.name }}</li>
</ul>
{% endfor %}

<h3><a href="{% url 'modify' person.id %}">Edit profile</a></h3>
{% endblock %}